package me.zoxymodz.core.utils;

import org.bukkit.inventory.ItemStack;

public enum HeadList {

	LENGENDAIRE("YWM0OWUwNjc2NTgyNzI5NjczNmRlODM3ZjUwZjBiZTdjMTk2NWM5OWU5ZGYwMGM1ODI0MzU2OWYwMWIxMDBmZCJ9fX0=","legendaire-skull"),
	SEIGNEUR("YjFiNmNhYTM2ZTRiYWRlOTc0MjkwNmU0MzhmNTBlYWVhM2MxNzBhNTM3ZWVlYjQxZDU1OGY1ZWFiNjU5ZTQyOCJ9fX0==","seigneur-skull"),
	MAITRE("NjEyZWY3ZTg4MjE2YjE0OWEwZDFmYTFlNTAzNWYwMTFhYWI3MTFiZWQwM2QwNjI3MDE0ZDE0YmE2YTNkZDE2NiJ9fX0===","maitre-skull"),
	ROI("YzIzMWFiYjEwZWUwZWNiYjA3NDEyYjM1MTA0ODZlMmIxMmIxNjMxZThhN2ZjZjkwMjk0NmRiYzFlYTA4MGQ2MiJ9fX0===","roi-skull"),
	DEMON("NGY2MTUyYzY0MzFkNGUzZjIzYmQ4Yzg1ZWQ4YzdjOGI1MTU0ZmMwMTI2ODMzMjkzNDhkNDY0NWJiODE4ZmQ3ZiJ9fX0=","demon-skull"),
	CHAMPION("NDc5Y2RmOTVhMWY1NDAzNDI3NGE0ODU3MWNiM2YyYjQ5Yzc0OGZiZjI0NzljMmIwZjZmMWQ0ZDdiNTg5MDRmIn19fQ===","champion-skull"),
	VIP("NjRiNTRmM2U2YTcwMTZhMTRlNzZlZWRjNTMwNDBmNDk2MDU4MWJhY2FjODE0ZmZiNTgxNmZhZTFhMTRiMDE4ZCJ9fX0=","vip-skull"),


	DISCORD("ZGM1OWU1YzdiMDczOGI1NzlmM2I0NDRjMTNhNDdiZWQ0OTZiMzA4MzhiMmVlMmIxMjdjYzU5Y2Q3OThhZWU3NyJ9fX0=","discord-skull"),
	BUSINESS("ZDY3ZGNlNDY0NTM0OWU0MWE3ZjM1Nzk3ZTJiOTI3OWUzNWE2NWY1ZTgxYTM0NDk2ODg1ZDI3MjY4ZjM2OTEzOSJ9fX0=","business-skull"),
	WARP("YzY5MTk2YjMzMGM2Yjg5NjJmMjNhZDU2MjdmYjZlY2NlNDcyZWFmNWM5ZDQ0Zjc5MWY2NzA5YzdkMGY0ZGVjZSJ9fX0=","warp-skull"),
	EVENT("ZjAwZTdiMzNlZTJhNjAwMjc1OGFjZmUwOGM3ZGY2YmQzN2E0OTdkYzlmODAwMGMzY2E5ODI0YTJjZmFiY2FkZCJ9fX0=","event-skull"),
	BF2W("NmNlZjlhYTE0ZTg4NDc3M2VhYzEzNGE0ZWU4OTcyMDYzZjQ2NmRlNjc4MzYzY2Y3YjFhMjFhODViNyJ9fX0=","bf2w-skull"),
	BVIP("NWM3MTJiMTk3MWM1ZjQyZWVmZjgwNTUxMTc5MjIwYzA4YjgyMTNlYWNiZTZiYzE5ZDIzOGMxM2Y4NmUyYzAifX19","bvip-skull"),


	OBJECT("NTg4MTQ5ZTU2Y2RlMDJlZWU2MjA5ODI4ODRiODkzNjM0NzU2YmU5MTQxZjJlMjc3N2I1MWNiMGE2NmMzMWRjZSJ9fX0=","object-skull"),
	GRADE("ODMzY2ZlNGY3ZjFlNTU0ZTQ0YzA4MzE2ODU2ZmM4YmE0ZjE4ODhmZmIyZmFlMTc4YmZjNzYzNGJlZDViOTliNyJ9fX0=","grade-skull"),
	COINS("ZjgwOWQyZTY5NjEwZjFlNmI3NWZlMGQ0NTk4ZTQ0MWU1NjAzMjVkMmQ1MmQ5N2NmNjY4NTljNDRmYTNkOGE3OSJ9fX0=","coins-skull"),
	ATOUTS("MjZhYTkzMDFjNTg4N2E5NDc0YTZhNWFkZTNjMTdlNGUyNDFhNjgwNDA1ODlhZGRkN2FhMmNlNjAwODBkMzc3NCJ9fX0=","atouts-skull"),
	RUBIS("YjMxNzUyODZjZDNiYTFhM2E5YzkwODI5NzdkMDlkZDM3YjE3N2FiZjM3YTQ2NjU4MGMyN2QxZGVlNzJiM2MxOCJ9fX0=","rubis-skull"),

	COEURS("ODU0MzE1OWZhN2ZmOGI1M2MyY2I4ZjMzYzQxYTM3N2FlZDZhY2U4MjY0NWM5Mzg1NjgzMDRkZDFjMzQifX19","coeurs-skull"),
	SPEED("MjI3OTYwZTk4ODk2ZDU5NGVmNTI0OTZlZmQ1ZDg0MjcyMjJlMjJmYWViZjJhN2U2NWFhZjZjNWFlMjI0NzM3In19fQ==","speed-skull"),
	RESISTANCE("ZDI2MTFhN2Y1YTc0YTVlMzc2ZGQzZTQ2ZGU2OWY3MmViYTg4OGZhZDNmMTk0MWZlOTBhZjZiNjI1ZmI0ODQ3MSJ9fX0=","resistance-skull"),
	HASTE("NTRlNDM1OGQ3MzRhNmUwNjhlYjA3Y2I4ZmM1ZmZkZThiOTQ4MDBlYjM5Njc3NzQyOGE0ZjU1OTMxNWExZmY0ZCJ9fX0=","haste-skull"),
	INVISIBILITE("NWQzZjNkOTA2MjUzMjFiYTE2NWYyODljYzNlZTE3ZGQ1ZjBlNTlmNzVlMDI5MDkwY2ZlMTM3NDZhZGMwNTJhZiJ9fX0=","invisibilite-skull"),

	RETOUR("NjllYTFkODYyNDdmNGFmMzUxZWQxODY2YmNhNmEzMDQwYTA2YzY4MTc3Yzc4ZTQyMzE2YTEwOThlNjBmYjdkMyJ9fX0=","retour-skull")
	;
	
	
	private final ItemStack item;
	
	private final String idTag;
	
	private String prefix = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUv";
	
	HeadList(String texture, String id) {
		
		item = CreateSkull.createSkull(prefix + texture, id);
        idTag = id;
		
	}

	public ItemStack getItemStack() {
        return item;
    }
    
    public String getName() {
        return idTag;
    }
	
}
